gantt
    title Časovnica - plan izvedbe
    dateFormat YYYY-MM-DD
    axisFormat %b %d

    section Phase 1: Planiranje
    Introduction & ter pobiranje zahtev :milestone, m1, 2026-02-13, 0d
    Podpis pogodbe :milestone, m2, 2026-02-13, 0d

    Inicialni osnutek predstavljen :milestone, m3, 2026-02-20, 0d
    Funkcijonalne zahteve definirane :milestone, m4, 2026-02-27, 0d

    section Phase 2: Razvojno okolje ter infrastruktura
    Razvojno okolje ter infrastruktura postavljena :milestone, m5, 2026-03-06, 0d

    section Phase 3: Razvoj aplikacije
    Prva verzija aplikacije :milestone, m6, 2026-03-13, 0d
    Končna verzija aplikacije :milestone, m7, 2026-03-27, 0d

    section Phase 4: Zaključek projekta
    Predaja ter zaključek projekta :milestone, m8, 2026-04-03, 0d